# Site settings
name: 成長地
email: shwpower@163.com
title: 成長地
author: Shen Wei
url: https://shwpower.github.io/
resume_site: 
github: github.com/shwpower
baseurl: 
description: 成长的地方
meta_description: 申伟;数据库;架构师;开发运维;互联网技术;DBA;MySQL;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 珍惜、享受爱与被爱

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: shwpower
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : shwpower
    disqus :
        short_name : shwpower
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light